### ISSUE TITLE
Action/Response .getTransport() broken due to Object.freeze()

### ISSUE THREAD

**Issue by rvegas** [kusanagi/katana-sdk-node#30]
Both in:
https://github.com/kusanagi/katana-sdk-node/blob/04f6755edbe1c39e2ac963c2424789dc50159adf/sdk/action.js#L48-L54

And in:
https://github.com/kusanagi/katana-sdk-node/blob/04f6755edbe1c39e2ac963c2424789dc50159adf/sdk/response.js#L83-L89

These calls to `Object.freeze()` are making the transport inaccessible in both classes.

From the documentation [here](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze), this is the cause:
`
// Both the object being passed as well as the returned
// object will be frozen. It is unnecessary to save the
// returned object in order to freeze the original.
`

@orestes I don't want to rush an issue so for now I'll just remove it.

**Comment by orestes** [comment]
Working on it

**Comment by rvegas** [comment]
🤦‍♂️  my bad, also implemented a similar solution. Checking yours @orestes

**Comment by rvegas** [comment]
Merged yours @orestes, thanks.
